const $ = (q) => document.querySelector(q);
const store = { get(k, v) { try { return JSON.parse(localStorage.getItem(k)) ?? v; } catch { return v; } }, set(k, v) { localStorage.setItem(k, JSON.stringify(v)); }, remove(k) { localStorage.removeItem(k); } };
const state = { pin: store.get("pp_direct_pin", ""), member: store.get("pp_direct_member", ""), screen: "now", filter: "all", orders: store.get("pp_direct_orders", []), catalogs: store.get("pp_direct_catalogs", { tipos: [], responsables: [], estados: [] }), offline: false };
const esc = (v = "") => String(v).replace(/[&<>'"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c]));
const active = () => state.orders.filter(o => !["Entregado", "Cancelado"].includes(o.estado));
const hours = o => o.entrega ? (new Date(o.entrega) - Date.now()) / 36e5 : Infinity;
function priority(o) { if (o.estado === "Bloqueado" || o.diseno === "No" || o.material === "No") return "blocked"; if (hours(o) <= 4) return "now"; if (hours(o) <= 24) return "today"; return "later"; }
const labels = { now: "Hacer ahora", today: "Hacer hoy", later: "Programar", blocked: "Bloqueado" };
const sort = (a,b) => ({ blocked:0, now:1, today:2, later:3 }[priority(a)] - { blocked:0, now:1, today:2, later:3 }[priority(b)]) || (new Date(a.entrega || "2999") - new Date(b.entrega || "2999"));
const dt = v => { const d = new Date(v); return v && !Number.isNaN(d) ? new Intl.DateTimeFormat("es-MX", { dateStyle:"medium", timeStyle:"short" }).format(d) : "Sin fecha"; };
function toast(t) { const n = $("#toast"); n.textContent = t; n.classList.add("show"); clearTimeout(window.t); window.t = setTimeout(() => n.classList.remove("show"), 3200); }
function api(action, data = {}) { return new Promise((resolve, reject) => { const url = window.PRIORIDAD_CONFIG?.appsScriptUrl || ""; if (!url.startsWith("https://")) return reject(new Error("Falta configurar la URL de Apps Script.")); const cb = `pp_callback_${Date.now()}_${Math.random().toString(36).slice(2)}`; const script = document.createElement("script"); const cleanup = () => { delete window[cb]; script.remove(); }; const timer = setTimeout(() => { cleanup(); reject(new Error("Google Sheets tardó demasiado en responder.")); }, 20000); window[cb] = (result) => { clearTimeout(timer); cleanup(); result.ok ? resolve(result) : reject(new Error(result.error || "No se pudo completar la operación.")); }; const payload = encodeURIComponent(JSON.stringify({ action, pin: state.pin, ...data })); script.src = `${url}${url.includes("?") ? "&" : "?"}callback=${cb}&payload=${payload}`; script.onerror = () => { clearTimeout(timer); cleanup(); reject(new Error("No se pudo conectar con Google Sheets.")); }; document.head.append(script); }); }
async function refresh(showToast = true) { $("#refresh").textContent="…"; try { const [list, cats] = await Promise.all([api("pwa_list_orders"), api("pwa_catalogs")]); state.orders = list.orders || []; state.catalogs = cats.catalogs || state.catalogs; state.offline=false; store.set("pp_direct_orders",state.orders);store.set("pp_direct_catalogs",state.catalogs);render(); if(showToast)toast("Cola actualizada."); } catch(e) { state.offline=true; render(); if(showToast)toast(e.message); } finally { $("#refresh").textContent="↻"; } }
function pill(o) { const p=priority(o);return `<span class="priority priority-${p}">${labels[p]}</span>`; }
function card(o,i) { return `<button class="order-card" data-action="detail" data-id="${esc(o.id)}"><div class="order-top"><div><h3>${i===undefined?"":`${i+1}. `}${esc(o.cliente||"Sin cliente")}</h3><p>${esc(o.tipo||"Sin tipo")}</p></div>${pill(o)}</div><div class="meta">Entrega: ${esc(dt(o.entrega))}<br/>Responsable: ${esc(o.responsable||"Sin asignar")} · ${esc(o.tiempoMinutos||0)} min</div></button>`; }
function mine() { return active().filter(o=>!state.member||o.responsable===state.member).sort(sort); }
function nowView(){const list=mine(),current=list[0], critical=active().filter(o=>["blocked","now"].includes(priority(o))).sort(sort);return `${state.offline?`<p class="offline">Mostrando la última cola guardada localmente.</p>`:""}${current?`<article class="hero-card"><p class="eyebrow">TU SIGUIENTE TRABAJO</p>${pill(current)}<h2>${esc(current.cliente)}</h2><p>${esc(current.tipo)} · Entrega ${esc(dt(current.entrega))}</p><div class="actions"><button class="action-button" data-action="update" data-id="${esc(current.id)}" data-key="estado" data-value="En proceso">Empezar</button><button class="action-button" data-action="detail" data-id="${esc(current.id)}">Ver detalle</button></div></article>`:`<div class="empty"><strong>Tu cola está al día</strong>Cuando haya una asignación para ${esc(state.member||"el equipo")}, aparecerá aquí.</div>`}<p class="section-heading">CRÍTICOS DEL EQUIPO</p><div class="order-list">${critical.map(card).join("")||`<div class="team-note">No hay bloqueos ni vencimientos inmediatos.</div>`}</div>`;}
function queueView(){
  const list=mine().filter(o=>state.filter==="all"||priority(o)===state.filter);
  const filters=[["all","Todo"],["now","Ahora"],["today","Hoy"],["blocked","Bloqueados"]];
  const controls=filters.map(([k,l])=>`<button class="filter ${state.filter===k?"active":""}" data-action="filter" data-filter="${k}">${l}</button>`).join("");
  const body=list.length?`<div class="order-list">${list.map(card).join("")}</div>`:`<div class="empty"><strong>No hay pedidos en este filtro</strong>Prueba otra categoría.</div>`;
  return `<div class="filter-row">${controls}</div>${body}`;
}
function teamView(){const people=state.catalogs.responsables||[],orders=active(),crit=orders.filter(o=>["blocked","now"].includes(priority(o))).sort(sort);return `<div class="actions"><button class="primary-button" data-action="new">＋ Registrar pedido</button></div><p class="section-heading">CARGA ACTUAL</p><div class="load-grid">${people.map(n=>{const q=orders.filter(o=>o.responsable===n);return `<div class="load-card"><strong>${esc(n)}</strong><span>${q.length} pedidos · ${q.reduce((s,o)=>s+Number(o.tiempoMinutos||0),0)} min</span></div>`}).join("")||`<div class="team-note">Configura responsables en el libro.</div>`}</div><p class="section-heading">REQUIEREN APOYO</p><div class="order-list">${crit.map(card).join("")||`<div class="team-note">No hay casos críticos.</div>`}</div>`;}
function settingsView(){const people=state.catalogs.responsables||[];return `<div class="card settings-card"><h3>Mi configuración</h3><p>Elige la cola que deseas consultar en este dispositivo.</p><div class="setting-line"><div><strong>Persona activa</strong><br/><small>${esc(state.member||"Sin seleccionar")}</small></div><select id="member-select"><option value="">Seleccionar</option>${people.map(n=>`<option ${n===state.member?"selected":""}>${esc(n)}</option>`).join("")}</select></div><div class="setting-line"><div><strong>Datos</strong><br/><small>${state.orders.length} pedidos en la última actualización.</small></div><button class="secondary-button" data-action="logout">Salir</button></div></div><p class="section-heading">ESTADO</p><div class="team-note">${state.offline?"Sin conexión. Pulsa actualizar al recuperar Internet.":"Conectada a Google Sheets."}</div>`;}
function render(){const names={now:"Ahora",queue:"Mi cola",team:"Equipo",settings:"Ajustes"};$("#screen-title").textContent=names[state.screen];$("#screen").innerHTML=({now:nowView,queue:queueView,team:teamView,settings:settingsView})[state.screen]();document.querySelectorAll(".nav-button").forEach(b=>b.classList.toggle("active",b.dataset.screen===state.screen));}
function open(html){const m=$("#modal");m.innerHTML=`<div class="modal-content">${html}</div>`;m.showModal();}function close(){ $("#modal").close(); }
function details(o){const editable=!state.member||o.responsable===state.member;open(`<div class="modal-head"><div><p class="eyebrow">${esc(o.id)}</p><h2>${esc(o.cliente)}</h2></div><button class="close-button" data-action="close">×</button></div><p style="color:var(--blue);font-weight:800">${esc(o.tipo)}</p><div class="detail-grid"><div class="detail-row"><span>ENTREGA</span><strong>${esc(dt(o.entrega))}</strong></div><div class="detail-row"><span>RESPONSABLE</span><strong>${esc(o.responsable||"Sin asignar")}</strong></div><div class="detail-row"><span>DESCRIPCIÓN</span><strong>${esc(o.descripcion||"Sin descripción")}</strong></div><div class="detail-row"><span>NOTAS</span><strong>${esc(o.notas||"Sin notas")}</strong></div><div class="detail-row"><span>PREPARACIÓN</span><strong>Diseño: ${esc(o.diseno)} · Material: ${esc(o.material)}</strong></div></div>${editable?`<div class="toggle-actions"><button data-action="update" data-id="${esc(o.id)}" data-key="estado" data-value="En proceso">Empezar</button><button data-action="update" data-id="${esc(o.id)}" data-key="estado" data-value="Entregado">Entregado</button><button class="danger" data-action="update" data-id="${esc(o.id)}" data-key="estado" data-value="Bloqueado">Bloquear</button><button data-action="update" data-id="${esc(o.id)}" data-key="diseno" data-value="${o.diseno==="Sí"?"No":"Sí"}">Diseño ${o.diseno==="Sí"?"pendiente":"listo"}</button><button data-action="update" data-id="${esc(o.id)}" data-key="material" data-value="${o.material==="Sí"?"No":"Sí"}">Material ${o.material==="Sí"?"pendiente":"listo"}</button><button data-action="note" data-id="${esc(o.id)}">Añadir nota</button></div>`:`<div class="team-note">Este pedido pertenece a otra persona.</div>`}`);}
function newForm(){const t=state.catalogs.tipos||[],p=state.catalogs.responsables||[];open(`<div class="modal-head"><h2>Nuevo pedido</h2><button class="close-button" data-action="close">×</button></div><form id="new-form" class="form-grid"><label class="field"><span class="field-label">CLIENTE</span><input name="cliente" required></label><label class="field"><span class="field-label">TIPO</span><select name="tipo">${t.map(x=>`<option>${esc(x)}</option>`).join("")||"<option>Otro</option>"}</select></label><div class="form-inline"><label class="field"><span class="field-label">FECHA</span><input type="date" name="fechaEntrega" required></label><label class="field"><span class="field-label">HORA</span><input type="time" name="horaEntrega" required></label></div><div class="form-inline"><label class="field"><span class="field-label">TIEMPO (MIN)</span><input type="number" min="1" name="tiempoMinutos" required></label><label class="field"><span class="field-label">CANTIDAD</span><input type="number" min="1" name="cantidad" value="1"></label></div><label class="field"><span class="field-label">RESPONSABLE</span><select name="responsable">${p.map(x=>`<option ${x===state.member?"selected":""}>${esc(x)}</option>`).join("")}</select></label><div class="form-inline"><label class="field"><span class="field-label">DISEÑO</span><select name="diseno"><option>Sí</option><option>No</option></select></label><label class="field"><span class="field-label">MATERIAL</span><select name="material"><option>Sí</option><option>No</option></select></label></div><label class="field"><span class="field-label">DESCRIPCIÓN</span><textarea name="descripcion"></textarea></label><label class="field"><span class="field-label">NOTAS</span><textarea name="notas"></textarea></label><div class="modal-footer"><button type="button" class="secondary-button" data-action="close">Cancelar</button><button class="primary-button">Registrar</button></div></form>`);$("#new-form").addEventListener("submit",async e=>{e.preventDefault();try{const r=await api("pwa_create_order",{form:Object.fromEntries(new FormData(e.currentTarget))});close();await refresh(false);toast(`Pedido ${r.result.id} registrado.`);}catch(x){toast(x.message);}});}
function noteForm(id){open(`<div class="modal-head"><h2>Registrar avance</h2><button class="close-button" data-action="close">×</button></div><form id="note-form" class="form-grid"><label class="field"><span class="field-label">NOTA OPERATIVA</span><textarea name="notes" required></textarea></label><div class="modal-footer"><button type="button" class="secondary-button" data-action="close">Cancelar</button><button class="primary-button">Guardar</button></div></form>`);$("#note-form").addEventListener("submit",async e=>{e.preventDefault();const n=new FormData(e.currentTarget).get("notes").toString(),o=state.orders.find(x=>x.id===id);try{await api("pwa_update_order",{id,changes:{notas:[o?.notas,n].filter(Boolean).join("\n• ")}});close();await refresh(false);toast("Nota guardada.");}catch(x){toast(x.message);}});}
document.addEventListener("click",async e=>{const b=e.target.closest("[data-action]");if(!b)return;const d=b.dataset;if(d.action==="close")return close();if(d.action==="detail"){const o=state.orders.find(x=>x.id===d.id);if(o)details(o);return;}if(d.action==="filter"){state.filter=d.filter;return render();}if(d.action==="new")return newForm();if(d.action==="note")return noteForm(d.id);if(d.action==="logout"){store.remove("pp_direct_pin");state.pin="";$("#workspace").classList.add("hidden");$("#unlock").classList.remove("hidden");return;}if(d.action==="update"){try{await api("pwa_update_order",{id:d.id,changes:{[d.key]:d.value}});close();await refresh(false);toast("Cambio guardado.");}catch(x){toast(x.message);}}});
$("#refresh").addEventListener("click",()=>refresh());document.querySelectorAll(".nav-button").forEach(b=>b.addEventListener("click",()=>{state.screen=b.dataset.screen;render();}));document.addEventListener("change",e=>{if(e.target.id==="member-select"){state.member=e.target.value;store.set("pp_direct_member",state.member);render();}});$("#unlock-form").addEventListener("submit",async e=>{e.preventDefault();state.pin=$("#team-pin").value.trim();$("#unlock-error").textContent="";try{await refresh(false);store.set("pp_direct_pin",state.pin);$("#unlock").classList.add("hidden");$("#workspace").classList.remove("hidden");render();}catch(x){$("#unlock-error").textContent=x.message;}});if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});if(state.pin){$("#unlock").classList.add("hidden");$("#workspace").classList.remove("hidden");render();refresh(false);}
